# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alunos/imagens', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Aluno_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='nome')),
                ('professor', models.CharField(max_length=100, verbose_name='Professor')),
                ('data_inicio', models.DateField(verbose_name='Inicio')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='curso', unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('sobre', models.TextField(blank=True, verbose_name='Sobre')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem')),
                ('alunos', models.ManyToManyField(blank=True, through='cursos.Aluno_curso', to='cursos.Aluno', verbose_name='alunos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.Categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_visivel', models.BooleanField(default=False, verbose_name='Visivel')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.Curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='modulo_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cursos.Modulo', verbose_name='modulo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='modulo_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cursos.Modulo', verbose_name='modulo'),
        ),
        migrations.AddField(
            model_name='aluno_curso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
    ]
